export { default as Home } from './home/Home'
export { default as Products } from './products/Products'
export { default as UserList } from './userList/UserList'
export { default as User } from './user/User'
export { default as NewUser } from './newUser/NewUser'